### ISSUE TITLE
Catch general panics so that the program does not crash

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#23] opened 2021-04-19 20:26 UTC
For #13 a panic handler was installed to handle panics in the model, rolling back changes to the state. Panics in the UI code itself can still make the application crash, as happens in the case of #21. Recovering from panics outside of the model code could be more complicated as the panic might have left the application in an inconsistent state. A mechanism that serialises the state and recovers from that in face of a crash (potentially the same as for hot reloading #20) might prevent this, but could be slow.

**Comment by jamievicary** [comment] 2021-04-19 20:30
Thanks I see. It's not a disaster for the system to crash if there's a panic. The most important thing is that the panic is alerted to the user, maybe even with an alert() if necessary. The point is that we will hopefully relatively quickly remove all the causes of panic.

**Comment by doctorn** [comment] 2021-04-21 16:13
It seems bizarre that you have so many panics in the first place. If you want to panic because you haven't implemented something it's best to use the `unimplemented!()` macro, otherwise I'd focus on threading everything through the `Result` monad rather than using handlers to catch panics.

`std::error::Error` makes this quite nice:

https://github.com/doctorn/cluster/blob/ac3985530354664c7143fe2404a29f8d04f1dcca/src/client/main.rs#L50-L120

https://github.com/doctorn/cluster/blob/ac3985530354664c7143fe2404a29f8d04f1dcca/src/client/main.rs#L233-L243

**Comment by zrho** [comment] 2021-04-21 16:24
The kind of error that leads to these panics coming up is internal errors like assertion failures, out of bounds array access and unwraps on options that really should be `Some` but are not because of logic errors. It wouldn’t make too much sense to have a `Result<Diagram, BrokenImplementation>` return type on all functions.

**Comment by doctorn** [comment] 2021-04-21 16:33
The vector to fixing the implementation is to handle those cases properly with results though isn't it?

**Comment by zrho** [comment] 2021-04-21 16:37
These errors should not come up. They are more complicated versions of a bug like `array[array.len()]`. The solution here would not involve returning an error type but instead amount to fixing the off by one error so that no out of bounds panic is produced anymore in the first place. The reason that there’s a lot of these panics happening at the moment is that Jamie is testing it quite thoroughly, which exposes bugs.

**Comment by doctorn** [comment] 2021-04-21 16:40
Ahh ok I see! Sorry!

**Comment by jamievicary** [comment] 2021-04-21 16:41
> Jamie is testing it quite thoroughly, which exposes bugs.

Lukas I have hardly started I assure you 😜

**Comment by jamievicary** [comment] 2021-04-21 16:43
Nathan, a bit more context: the project has only recently got to the stage where we can start to actually run the tool for its intended purpose, and hence discover all these little issues for the first time. Hopefully they'll be rapidly cleared up (or at least, hopefully a time will soon come where they are being cleared up faster than they are discovered!)

**Comment by jamievicary** [comment] 2021-04-30 16:24
Shall we close this now? We're not getting very many panics any more.

**Closed** 2021-05-19 17:12 UTC
Labels: enhancement
