### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#841] opened 2022-09-21 11:11 UTC
In this workspace, I try to do a contraction in a slice and the tool crashes. 
[88.zip](https://github.com/homotopy-io/homotopy-rs/files/9615980/88.zip)

**Comment by calintat** [comment] 2022-09-21 12:32
I can't reproduce a crash. What's the contraction?

**Comment by mlharaujo** [comment] 2022-09-21 12:41
I go into Singular 12, then Singular 4, where I see this: 
![image](https://user-images.githubusercontent.com/36002049/191506087-d02202fa-16d1-4fc6-ac05-e6c09acfa9a4.png)

Now I click the dot on the bottom and drag it right and up.

**Comment by calintat** [comment] 2022-09-21 12:46
Sorry it's a bit confusing that the action dump gives a different workspace to the hom file. That's because of my recent change to the "undo" behaviour which I just reverted. Unfortunately that means this action dump is now useless.

I was able to reproduce it using the hom file. It's a "malformed rewrite" error :(

**Comment by calintat** [comment] 2022-10-06 08:41
Unfortunately this is still reproducible despite the latest fixes. It would be nice if we could find a smaller example.

**Comment by NickHu** [comment] 2022-11-10 12:51
We have made even more changes recently, and this workspace is no longer importable. Is it still reproducible?

**Comment by mlharaujo** [comment] 2022-11-10 13:55
I can try to build the diagram again, but it will take a while.

**Comment by mlharaujo** [comment] 2022-11-11 16:46
I tried again to build the double figure 8, which I was able to do. Then I tried to prove that twice the double figure 8 can be contracted down to the identity and got this crash. 
[homotopy_io_crash_action_dump.txt](https://github.com/homotopy-io/homotopy-rs/files/9991742/homotopy_io_crash_action_dump.txt)

**Comment by mlharaujo** [comment] 2022-11-11 17:24
I forgot to save the workspace before it crashed, so I only have the dump...

**Comment by mlharaujo** [comment] 2022-11-12 17:06
In the workspace below, I get a crash when I try to drag up the cell in singular slice 13.

[88.zip](https://github.com/homotopy-io/homotopy-rs/files/9995484/88.zip)

**Comment by calintat** [comment] 2022-11-12 20:18
Thanks Manuel!

**Comment by calintat** [comment] 2022-11-12 20:20
@NickHu the crash seems to originate in the new code we added yesterday:
https://github.com/homotopy-io/homotopy-rs/blob/23e57c2224ff262e2b9e12fde2e452500700721f/homotopy-core/src/contraction.rs#L874-L883

Maybe there are examples where max_ix doesn't have nodes to its left? We could take max_ix to be the source in that case.

**Comment by NickHu** [comment] 2022-11-12 20:42
I had assumed that the max dimensional generator always lives in a singular slice, especially as we pick one that's an external node within the graph. I'm not sure why this would be invalidated.

**Comment by calintat** [comment] 2022-11-12 20:47
Yeah, so this is what the restriction graph looks like and you can see the max dimensional node doesn't have any neighbours to the left or right, so in that case we should pick max_ix to be both source_ix and target_ix.

![IMG_2E3AAD96504E-1](https://user-images.githubusercontent.com/16837293/201493947-ff2bddad-c67d-4eac-827b-c55029bca4bb.jpeg)

**Comment by calintat** [comment] 2022-11-12 20:53
I pushed a change which fixes this.

@mlharaujo did this crash in the same place as the original workspace? If so, we can close this!

**Comment by mlharaujo** [comment] 2022-11-12 20:57
I can't remember where the original one crashed, so we might as well close it...

**Comment by calintat** [comment] 2022-11-12 21:06
Sounds good to me!

**Closed by calintat** 2022-11-12 21:06 UTC
Labels: bug, invertible
