### ISSUE TITLE
Passing a unit through a braiding corrupts its labels

### ISSUE THREAD

**Issue by doctorn** [homotopy-io/homotopy-rs#840] opened 2022-09-21 09:45 UTC
I have an invertible generator

<img width="239" alt="Screenshot 2022-09-21 at 10 40 47" src="https://user-images.githubusercontent.com/6421560/191471872-4dc20c63-1707-429e-a4d6-6070633de200.png"> $:$ <img width="240" alt="Screenshot 2022-09-21 at 10 40 14" src="https://user-images.githubusercontent.com/6421560/191471966-495b3541-d011-492b-a9a9-d8a97ce88038.png"> $\xrightarrow{\simeq}$ <img width="161" alt="Screenshot 2022-09-21 at 10 40 27" src="https://user-images.githubusercontent.com/6421560/191472070-8ac93989-eb9b-4f55-8d6a-7f03f3dd4395.png">

However, I can't click-to-attach it in the diagram:

<img width="241" alt="Screenshot 2022-09-21 at 10 39 37" src="https://user-images.githubusercontent.com/6421560/191472254-ae1cd5b0-4d87-403c-abb5-6e4e3b90d2a6.png">

Workspace and actions:
[Archive.zip](https://github.com/homotopy-io/homotopy-rs/files/9615354/Archive.zip)

**Comment by calintat** [comment] 2022-09-21 12:36
Whenever you can't click to attach, it means the labels have become corrupted in some way, most likely caused by contraction. But this is a really long proof and it's hard to tell where that happened.

I see this as even more evidence that we need typechecking asap.

**Comment by doctorn** [comment] 2022-09-28 11:13
Minimised workspace:

[homotopy_io_export (1).hom.zip](https://github.com/homotopy-io/homotopy-rs/files/9664327/homotopy_io_export.1.hom.zip)

**Comment by doctorn** [comment] 2022-10-01 08:42
I assume this is deeply connected to #856

**Comment by calintat** [comment] 2022-10-06 08:47
Unfortunately this is still reproducible, and it's not connected to #856 as that's a contraction in a singular slice whereas this is a top-level contraction. The neighbourhood of the unit is corrupted after this contraction/expansion move:
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/194266021-97e73488-cf1f-42c2-98a3-ef82ad6fccc6.svg) ![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/194266076-e59adb89-8e64-4c55-a4bc-b8328401d1ec.svg) ![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/194266026-2fd87e29-745c-4eba-9f75-8302a390c6ce.svg)

**Comment by doctorn** [comment] 2022-10-13 14:35
Any updates on this?

**Comment by calintat** [comment] 2022-11-02 10:47
So this contraction still doesn't typecheck:

![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/199470158-313d4c32-3f75-4621-b82d-2ae5ae869bb5.svg) ![homotopy_io_export(3)](https://user-images.githubusercontent.com/16837293/199470178-8048e2c2-9199-4be5-9fe2-7d1e8baf2820.svg)

Interestingly, you can do it if you first braid the unit and the wire:

![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/199470158-313d4c32-3f75-4621-b82d-2ae5ae869bb5.svg) ![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/199470304-7c622baf-580b-4830-96ec-48c06f94804b.svg) ![homotopy_io_export(3)](https://user-images.githubusercontent.com/16837293/199470178-8048e2c2-9199-4be5-9fe2-7d1e8baf2820.svg)

Maybe this is not a problem?

**Comment by jamievicary** [comment] 2022-11-02 10:49
Can you contract that two-step proof to produce a single-step move?

**Comment by jamievicary** [comment] 2022-11-02 10:50
Is everything live on alpha so I can test some things?

**Comment by calintat** [comment] 2022-11-02 10:51
Yes, everything is live on alpha (with typechecking enabled so you can't do illegal contractions).

**Comment by calintat** [comment] 2022-11-02 10:51
> Can you contract that two-step proof to produce a single-step move?

Yes you can!

**Comment by jamievicary** [comment] 2022-11-02 10:52
> > Can you contract that two-step proof to produce a single-step move?
> 
> Yes you can!

Then something weird is going on -- the contraction of that two-step proof should be precisely the original 1-step proof that the typechecker rejected. Clearly the direct contraction is doing something weird with the labels.

**Comment by calintat** [comment] 2022-11-02 10:54
Yeah I checked the neighbourhoods and indeed two of the labels are different.

**Comment by calintat** [comment] 2022-11-11 15:45
Fixed by 1100b674c414400c962837d792dcd744f557bf1f

**Closed by calintat** 2022-11-11 15:45 UTC
Labels: bug, invertible
