### ISSUE TITLE
Expansion not preserving label neighbourhood

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#856] opened 2022-09-30 17:16 UTC
Doing this contraction then expansion in 3D does not preserve the label neighbourhood of the (yellow) 3D scalar:

![one](https://user-images.githubusercontent.com/450276/193322476-464968fd-4798-446b-b264-450e0e830ada.svg)→![two](https://user-images.githubusercontent.com/450276/193322490-b0b24d29-25b7-415b-886f-d64da4aae2be.svg)→![three](https://user-images.githubusercontent.com/450276/193322502-4257a030-49c6-4543-a7dc-5f606e381a34.svg)

I think the bug is probably in expansion.

Data diff (left (red) is expected original neighbourhood, right (green) is observed incorrect neighbourhood):

```diff
Diff < left / right > :
 DiagramN {
     source: DiagramN {
         source: DiagramN {
             source: Diagram0(
                 0:0⁺,
             ),
             cospans: [],
         },
         cospans: [],
     },
     cospans: [
         Cospan {
             forward: RewriteN {
                 dimension: 2,
                 cones: [
                     Cone {
                         index: 0,
                         internal: ConeInternal {
                             source: [],
                             target: Cospan {
                                 forward: RewriteN {
                                     dimension: 1,
                                     cones: [
                                         Cone {
                                             index: 0,
                                             internal: ConeInternal {
                                                 source: [],
                                                 target: Cospan {
                                                     forward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Source,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                     backward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Target,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                 },
                                                 regular_slices: [
                                                     Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Source,
                                                                     1,
                                                                 ),
                                                                 [
                                                                     Regular(
                                                                         0,
                                                                     ),
                                                                 ],
                                                             ),
                                                         ),
                                                     ),
                                                 ],
                                                 singular_slices: [],
                                             },
                                         },
                                     ],
                                 },
                                 backward: RewriteN {
                                     dimension: 1,
                                     cones: [
                                         Cone {
                                             index: 0,
                                             internal: ConeInternal {
                                                 source: [],
                                                 target: Cospan {
                                                     forward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Source,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                     backward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Target,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                 },
                                                 regular_slices: [
                                                     Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Target,
                                                                     1,
                                                                 ),
                                                                 [
                                                                     Regular(
                                                                         0,
                                                                     ),
                                                                 ],
                                                             ),
                                                         ),
                                                     ),
                                                 ],
                                                 singular_slices: [],
                                             },
                                         },
                                     ],
                                 },
                             },
                             regular_slices: [
                                 RewriteN {
                                     dimension: 1,
                                     cones: [
                                         Cone {
                                             index: 0,
                                             internal: ConeInternal {
                                                 source: [],
                                                 target: Cospan {
                                                     forward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Source,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                     backward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Target,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                 },
                                                 regular_slices: [
                                                     Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Source,
<                                                                    0,
>                                                                    1,
                                                                 ),
                                                                 [
                                                                     Regular(
                                                                         0,
                                                                     ),
<                                                                    Regular(
<                                                                        0,
<                                                                    ),
                                                                 ],
                                                             ),
                                                         ),
                                                     ),
                                                 ],
                                                 singular_slices: [],
                                             },
                                         },
                                     ],
                                 },
                             ],
                             singular_slices: [],
                         },
                     },
                 ],
             },
             backward: RewriteN {
                 dimension: 2,
                 cones: [
                     Cone {
                         index: 0,
                         internal: ConeInternal {
                             source: [],
                             target: Cospan {
                                 forward: RewriteN {
                                     dimension: 1,
                                     cones: [
                                         Cone {
                                             index: 0,
                                             internal: ConeInternal {
                                                 source: [],
                                                 target: Cospan {
                                                     forward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Source,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                     backward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Target,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                 },
                                                 regular_slices: [
                                                     Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Source,
                                                                     1,
                                                                 ),
                                                                 [
                                                                     Regular(
                                                                         0,
                                                                     ),
                                                                 ],
                                                             ),
                                                         ),
                                                     ),
                                                 ],
                                                 singular_slices: [],
                                             },
                                         },
                                     ],
                                 },
                                 backward: RewriteN {
                                     dimension: 1,
                                     cones: [
                                         Cone {
                                             index: 0,
                                             internal: ConeInternal {
                                                 source: [],
                                                 target: Cospan {
                                                     forward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Source,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                     backward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Target,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                 },
                                                 regular_slices: [
                                                     Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Target,
                                                                     1,
                                                                 ),
                                                                 [
                                                                     Regular(
                                                                         0,
                                                                     ),
                                                                 ],
                                                             ),
                                                         ),
                                                     ),
                                                 ],
                                                 singular_slices: [],
                                             },
                                         },
                                     ],
                                 },
                             },
                             regular_slices: [
                                 RewriteN {
                                     dimension: 1,
                                     cones: [
                                         Cone {
                                             index: 0,
                                             internal: ConeInternal {
                                                 source: [],
                                                 target: Cospan {
                                                     forward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Source,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                     backward: Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
                                                                     Target,
                                                                     2,
                                                                 ),
                                                                 [],
                                                             ),
                                                         ),
                                                     ),
                                                 },
                                                 regular_slices: [
                                                     Rewrite0(
                                                         0:0⁺,
                                                         2:3⁺,
                                                         Some(
                                                             (
                                                                 2,
                                                                 BoundaryPath(
<                                                                    Target,
<                                                                    0,
>                                                                    Source,
>                                                                    1,
                                                                 ),
                                                                 [
<                                                                    Regular(
<                                                                        0,
<                                                                    ),
                                                                     Regular(
                                                                         0,
                                                                     ),
                                                                 ],
                                                             ),
                                                         ),
                                                     ),
                                                 ],
                                                 singular_slices: [],
                                             },
                                         },
                                     ],
                                 },
                             ],
                             singular_slices: [],
                         },
                     },
                 ],
             },
         },
     ],
 }
```

**Comment by calintat** [comment] 2022-10-06 08:40
This was caused by e9637e4078870f0d585b5ece60b1e31a8945e268 which we are reverting, so I am closing this.

**Closed by calintat** 2022-10-06 08:40 UTC
Labels: bug, invertible
