### ISSUE TITLE
Sort signature elements by dimension

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#10] opened 2021-04-19 16:57 UTC
Before we implement any more sophisticated ways of organising the signature (like groups, search, or configurable ordering) the signature should be ordered lexicographically by the dimension of the generator first and the name second.

**Comment by jamievicary** [comment] 2021-04-21 14:50
Seems to now be broken, perhaps related to recent work on #6

**Comment by NickHu** [comment] 2021-04-21 17:23
I can't reproduce this - everything is still sorted for me (on commit 1bede433996e8e3c4861ba6bbb8a90232e8d54aa)

**Comment by jamievicary** [comment] 2021-04-21 19:41
I also cannot reproduce it, I'll reopen with a video if it happens to me again. Closing for now.

**Closed by jamievicary** 2021-04-21 19:41 UTC
Labels: enhancement
