### ISSUE TITLE
Crash on triple figure 8 5-diagram

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#831] opened 2022-09-16 16:22 UTC
In the attached workspace, I drag the centre right strand over the centre left one creating a half braid. Then I drag again to try to create  a full braid and the tool crashes. Attaching workspace and crash dump.

![image](https://user-images.githubusercontent.com/36002049/190685081-9092a879-ae95-4dae-ad5e-7925e4ec93a9.png)

[triple_fig_8.zip](https://github.com/homotopy-io/homotopy-rs/files/9585667/triple_fig_8.zip)

**Comment by calintat** [comment] 2022-09-16 16:28
Weird, this seems to work for me. Is this what you meant?

![homotopy_io_export(3)](https://user-images.githubusercontent.com/16837293/190686000-5744ccd0-f6cd-4c44-9878-c1c4a2b2ba4e.svg)

I tried importing the action dump but that crashed with "invalid action". @regular-citizen what does that mean?

**Comment by mlharaujo** [comment] 2022-09-16 16:42
Yes I meant exactly that! I got it to work by going in the slice and doing it there, but it crashes when I do it in this projected view.

**Comment by calintat** [comment] 2022-09-16 17:12
I did it in the projected view though...

**Comment by mlharaujo** [comment] 2022-09-16 17:37
That's weird. I tried it again and it crashed again...

**Comment by regular-citizen** [comment] 2022-09-16 17:40
> I tried importing the action dump but that fails with "invalid action". @regular-citizen what does that mean?

Invalid action is raised whenever one of the actions to replay is not valid with respect to the proof state that is being replayed (homotopy-web/src/model.rs:261).

This is very very weird though. The action dump starts with a descend slice followed by a homotopy, without ever creating generators. So it definitely looks corrupted to me.

I don't know what could be causing it. My logic to keep history consistent with exfiltrated actions should be working, so this really should never be happening.

**Comment by calintat** [comment] 2022-09-17 09:38
It could be that the workspace was exported and then reimported which destroyed the history.

**Comment by calintat** [comment] 2022-09-17 09:39
I think action dumps should contain the proof state at the start. We can't always assume the start state is the empty proof.

**Comment by mlharaujo** [comment] 2022-09-17 09:40
> It could be that the workspace was exported and then reimported which destroyed the history.

Yes, I didn't do all of this in one go. I had to export and then import to keep working on it. Should I try to do it all in one go?

**Comment by mlharaujo** [comment] 2022-09-17 09:42
Is it enough if I import the signature but then build the diagram from scratch using that signature, or do I really have to build everything from scratch in one session?

**Comment by calintat** [comment] 2022-09-17 09:47
For the action dump to work, you'd need to everything in one go. But don't worry about it, we have the hom file which is enough.

**Comment by calintat** [comment] 2022-10-06 08:48
@mlharaujo do you remember how to reproduce this?

Unfortunately the action dump is invalid (due to a bug that's now been fixed) but the hom file still works.

**Comment by mlharaujo** [comment] 2022-10-06 09:14
Yes, I can try it now.

**Comment by regular-citizen** [comment] 2022-10-06 10:16
> I didn't do it all from scratch. I can do that if needed, but it will take a while.

No need, the new version of action dumps includes imports.

**Comment by calintat** [comment] 2022-10-06 10:43
Ugh the import failed again!

**Comment by calintat** [comment] 2022-10-06 10:46
@regular-citizen can you check this too? I'm not sure I understand why it fails.

**Comment by NickHu** [comment] 2022-10-06 13:12
Is it because the compression PR got merged recently?

**Comment by NickHu** [comment] 2022-11-10 12:52
Sorry, as with the other issue, we can't import this anymore... is the crash still observable?

**Comment by mlharaujo** [comment] 2022-11-10 13:56
I can try to build the diagram again, but it will take a while.

**Comment by calintat** [comment] 2022-12-09 14:33
@mlharaujo I feel like you said you couldn't reproduce this anymore, is that right?

**Comment by calintat** [comment] 2022-12-09 14:34
The file is named "triple figure 8", is it related to any of the examples you've been working on recently?

**Comment by mlharaujo** [comment] 2022-12-09 20:14
The recent example was the double figure 8. This is the triple figure 8, so it's one dimension higher. I haven't tried to build it again yet. I can try to do that in the next few days.

**Comment by mlharaujo** [comment] 2022-12-10 09:51
I just reproduced it. I'm attaching the workspace. I'm attaching the .hom file and action log. Note that to get the crash you need to click the half braid and drag left. 
[Uploading 888.zip…]()
[hom.zip](https://github.com/homotopy-io/homotopy-rs/files/10199700/hom.zip)

**Comment by mlharaujo** [comment] 2022-12-10 10:04
Here is a much smaller example. Again click on the half braid and drag left.
[minimal_crash.zip](https://github.com/homotopy-io/homotopy-rs/files/10199840/minimal_crash.zip)

**Comment by mlharaujo** [comment] 2022-12-10 10:07
By the way, I think the  reason you couldn't reproduce it before (@calintat ) is that I had not explained the move properly. If you click at the top of the diagram you get the full braid (in two steps), no crash.

**Comment by calintat** [comment] 2022-12-10 10:12
I see, so it's exactly the same issue as #947. You even constructed the same minimal example as I did.

**Comment by mlharaujo** [comment] 2022-12-10 10:24
Ah yes, that's right, I hadn't noticed!

**Comment by calintat** [comment] 2022-12-10 11:03
@mlharaujo I fixed the bug with the half-braid, so this should be fine now!

**Comment by calintat** [comment] 2022-12-10 11:11
Fixed by 50b209c442ca5370ab8eb64c32ae7b305a146a67

**Comment by mlharaujo** [comment] 2022-12-10 11:11
Just checked and it works now! What was the problem?

**Closed by calintat** 2022-12-10 11:11 UTC
Labels: bug, invertible

**Comment by calintat** [comment] 2022-12-10 11:14
It was a weird edge case in factorization.
