### ISSUE TITLE
Tool crashed and "Donwload action log" button doesn't work

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#911] opened 2022-11-21 14:38 UTC
I opened the console and copied the error messages to this notepad. Unfortunately I don't have the proof state I was working on, since I wasn't expecting a crash.

[console.txt](https://github.com/homotopy-io/homotopy-rs/files/10057377/console.txt)

![image](https://user-images.githubusercontent.com/36002049/203081105-4daaeda0-ec81-4109-984c-60e8d84f4823.png)

**Comment by regular-citizen** [comment] 2022-11-21 17:42
Oof this is due to a out of memory error ("Uncaught InternalError: allocation size overflow" showing up in the logs) on the JS side when dumping out the log file. I'm amazed that action dumps are that big, but it makes sense that it could happen.

The actual panic was cause by Cone::new in homotopy-core/src/rewrite.rs. In particular the first assertion of the method seems to be exploding:
https://github.com/homotopy-io/homotopy-rs/blob/98f4ef7d9dd4b4e06a406a686d3ee8ecad8f1d0c/homotopy-core/src/rewrite.rs#L906

**Comment by regular-citizen** [comment] 2022-11-21 17:50
Oh I think the culprit is that now imports get included in the action dumps (as part of #831 fix). That means that if you reimport the same meg-sized .hom file multiple times, an action dump will tend to error out of memory. That should be a quick fix though.

The real fix would be to try not to store action dumps in RAM but in local storage.

**Comment by mlharaujo** [comment] 2022-11-22 10:13
So this explains the problem with the action log, but the not the crash itself, right?

**Comment by regular-citizen** [comment] 2022-11-23 09:51
Yes, that is the case.

**Comment by mlharaujo** [comment] 2022-11-28 09:39
A similar thing has happened again, I'm not sure if it's the same problem. When I try to do an expansion in the diagram below, to resolve the half braid into a full braid, the tool crashes. I get the spinning wheel and no option to download action logs. 
![image](https://user-images.githubusercontent.com/36002049/204244184-1b657499-31e3-4f10-a96c-f08b32c52e9a.png)

I'm attaching the .hom file and the console output.

[coherence_laws_2.zip](https://github.com/homotopy-io/homotopy-rs/files/10102341/coherence_laws_2.zip)
[console.txt](https://github.com/homotopy-io/homotopy-rs/files/10102345/console.txt)

**Comment by mlharaujo** [comment] 2022-11-28 10:43
Same thing happened again, but this time there is a very short console output. I had clicked the top right dot and dragged down in the diagram below.
![image](https://user-images.githubusercontent.com/36002049/204257759-8636479e-10be-4c13-852b-bc1b9465da99.png)

Console output:

INFO homotopy-web/src/app.rs:138 Received action: Proof(Homotopy(Contract(Contract { bias: Some(Same), location: [], height: 3, direction: Backward }))) [homotopy_web.js:812:17](https://homotopy-rs--homotopy-io-labelled-xvbfeqnk.web.app/homotopy_web.js)
Uncaught (in promise) RuntimeError: unreachable executed
    __wbg_adapter_60 https://homotopy-rs--homotopy-io-labelled-xvbfeqnk.web.app/homotopy_web.js:277
    real https://homotopy-rs--homotopy-io-labelled-xvbfeqnk.web.app/homotopy_web.js:229
[homotopy_web_bg.wasm:3414641:1](https://homotopy-rs--homotopy-io-labelled-xvbfeqnk.web.app/homotopy_web_bg.wasm)

Attaching workspace. 
[coherence_laws_4.zip](https://github.com/homotopy-io/homotopy-rs/files/10102871/coherence_laws_4.zip)

**Comment by mlharaujo** [comment] 2022-11-28 10:46
But when I open a new tab, import the same workspace and try the same contraction, it works.

**Comment by calintat** [comment] 2022-11-28 12:35
> A similar thing has happened again, I'm not sure if it's the same problem. When I try to do an expansion in the diagram below, to resolve the half braid into a full braid, the tool crashes. I get the spinning wheel and no option to download action logs. 
> 
> ![image](https://user-images.githubusercontent.com/36002049/204244184-1b657499-31e3-4f10-a96c-f08b32c52e9a.png)
> 
> 
> 
> I'm attaching the .hom file and the console output.
> 
> 
> 
> [coherence_laws_2.zip](https://github.com/homotopy-io/homotopy-rs/files/10102341/coherence_laws_2.zip)
> 
> [console.txt](https://github.com/homotopy-io/homotopy-rs/files/10102345/console.txt)
> 
> 

I'm afraid that's just a case of the expansion taking too long to compute. We could add a timeout I suppose, but technically this is not a bug.

**Comment by jamievicary** [comment] 2022-11-28 13:34
But expansion is algorithmically trivial. So I think this should be investigated.

**Comment by mlharaujo** [comment] 2022-11-28 13:56
> > A similar thing has happened again, I'm not sure if it's the same problem. When I try to do an expansion in the diagram below, to resolve the half braid into a full braid, the tool crashes. I get the spinning wheel and no option to download action logs.
> > ![image](https://user-images.githubusercontent.com/36002049/204244184-1b657499-31e3-4f10-a96c-f08b32c52e9a.png)
> > I'm attaching the .hom file and the console output.
> > [coherence_laws_2.zip](https://github.com/homotopy-io/homotopy-rs/files/10102341/coherence_laws_2.zip)
> > [console.txt](https://github.com/homotopy-io/homotopy-rs/files/10102345/console.txt)
> 
> I'm afraid that's just a case of the expansion taking too long to compute. We could add a timeout I suppose, but technically this is not a bug.

The point is the wheel was still spinning but I think the actual computation stopped.

**Comment by jamievicary** [comment] 2022-11-28 14:02
To trigger this bug you have to click on the nontrivial intersection point in the singular slice, and drag left. This is quite low dimensional, it is definitely a bug. This is expansion in a singular slice, so it should try to do factorization, and if that fails it should bubble. The intended resolution here is bubbling. So most likely this is getting trapped in a factorization check. We need to check factorization is working as expected here.

**Comment by calintat** [comment] 2022-11-28 17:02
> A similar thing has happened again, I'm not sure if it's the same problem. When I try to do an expansion in the diagram below, to resolve the half braid into a full braid, the tool crashes. I get the spinning wheel and no option to download action logs. ![image](https://user-images.githubusercontent.com/36002049/204244184-1b657499-31e3-4f10-a96c-f08b32c52e9a.png)
> 
> I'm attaching the .hom file and the console output.
> 
> [coherence_laws_2.zip](https://github.com/homotopy-io/homotopy-rs/files/10102341/coherence_laws_2.zip) [console.txt](https://github.com/homotopy-io/homotopy-rs/files/10102345/console.txt)

Sorry I misunderstood what happened here. This *is* a crash unfortunately. The reason the panic handler didn't work is because Nick broke it when he implemented the spinner but I believe Chiara is working on a fix (@regular-citizen).

**Comment by calintat** [comment] 2022-12-09 14:29
I managed to reproduce the bug with a smaller example in #947.

Since this issue was primarily about the panic handler, I will close it.

**Closed by calintat** 2022-12-09 14:29 UTC
Labels: bug
