### ISSUE TITLE
Mesh incorrectly built for pants unit

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#189] opened 2021-09-28 12:16 UTC
The issue is most visible for low subdivision level.

[filename_todo (48).zip](https://github.com/homotopy-io/homotopy-rs/files/7243858/filename_todo.48.zip)
![homotopy io - Google Chrome 28_09_2021 13_14_06](https://user-images.githubusercontent.com/10602270/135084880-48cff90a-9a75-4ad2-bbe0-dd96322a0377.png)

**Comment by doctorn** [comment] 2021-09-28 19:17
I've spent an hour or so looking at this this evening and I still have absolutely no idea what the problem is. I'm going to work on mesh splitting as a priority and then come back to this when I've had a think about how to go about debugging it properly.

**Comment by jamievicary** [comment] 2021-09-29 10:16
Thanks for looking at it Nathan.

**Comment by jamievicary** [comment] 2021-12-06 18:18
Nathan can you explain again what this issue is. Is it the problem of, for a given cubical 3d mesh embedded in 4d, extracting the triangles that appear in any timeslice?

**Comment by doctorn** [comment] 2021-12-06 18:27
I wish I knew... I think it has to do with mesh extraction (as in some cubes that aren't being extracted from the cubical graph), but it could also be a typo anywhere in the rendering pipeline.

**Comment by calintat** [comment] 2022-01-11 16:58
@doctorn what's the smallest example where this happens?

**Comment by doctorn** [comment] 2022-01-11 23:39
I think lips 2 is a good start!
[lips_2.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/7850495/lips_2.hom.zip)

**Comment by calintat** [comment] 2022-01-12 12:41
Interesting, I tried removing the boundary from the mesh to make it easier to debug and now it looks fine. Which is very bizarre, since the boundary only contains non-degenerate cubes.

**Comment by calintat** [comment] 2022-01-12 12:44
But the pants unit is still broken so I might do that one instead since it's a smaller mesh.

**Comment by calintat** [comment] 2022-01-19 14:46
Since this is two separate issues, I am going to close this in favour of #339 and #349.

**Closed by calintat** 2022-01-19 14:46 UTC
Labels: bug, priority, graphics
