### ISSUE TITLE
Mouse hover tooltips broken in Chrome

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#233] opened 2021-11-22 16:44 UTC
Still working in Firefox

**Comment by jamievicary** [comment] 2021-11-23 15:32
This is working now in chrome, maybe it was a blip on my machine.

**Comment by jamievicary** [comment] 2021-11-25 19:04
OK I now see what's going on. The mouse hover tooltips do not appear when the sidebar is open. (Maybe they are under the sidebar?) Please can this be fixed.

**Comment by calintat** [comment] 2021-11-30 10:21
I'll close this since it's a duplicate of #248.

**Closed by calintat** 2021-11-30 10:21 UTC
Labels: bug
