### ISSUE TITLE
Unbraiding units

### ISSUE THREAD

**Issue by doctorn** [homotopy-io/homotopy-rs#759] opened 2022-08-29 13:48 UTC
I should be able to unbraid this:

![Screenshot 2022-08-29 at 14 46 27](https://user-images.githubusercontent.com/6421560/187216109-97ceff52-b706-43df-8291-0a4da023025b.png) $\rightarrow$ ![Screenshot 2022-08-29 at 14 46 43](https://user-images.githubusercontent.com/6421560/187216207-d64cc04c-debf-46bd-a61a-2c2e7791f076.png)

At the moment I'm seeing a toast that says 'label inconsistency'.

[minimised.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/9445063/minimised.hom.zip)

**Comment by NickHu** [comment] 2022-08-29 14:51
Probable instance of #751

**Comment by calintat** [comment] 2022-08-29 15:10
The error is however thrown by Nick's new code so it's likely caused by that. The other bug is older.

**Comment by NickHu** [comment] 2022-09-02 11:56
Partially fixed by c8ed52f1674256f968413c3be78e92b0de44c91a (Now you can contract it all together, but the expansion is still broken)

**Comment by jamievicary** [comment] 2022-09-02 12:06
Thanks for investigating this Nick. This needs closer attention as the
failure to unbraid could be due to incorrect labelling created by the
contraction algorithm. Calin maybe this would be good for you to look at?

**Comment by calintat** [comment] 2022-09-02 12:08
I think the easier example to check is unbraiding a scalar and a wire. It still doesn't work.

**Comment by jamievicary** [comment] 2022-09-02 12:19
Yes that's definitely easier and more important to check. Can you look
closely at the contracted diagram and see if the scalar has the correct
neighborhood. This is easy to check we did it quite quickly already the
other day for the previous build.

**Comment by calintat** [comment] 2022-09-10 10:22
Fixed by a29cb882d428be11782233064da027d623d348c2

**Closed by calintat** 2022-09-10 10:22 UTC
Labels: bug, invertible
