### ISSUE TITLE
Clicking in the attachment strip should only allow attachment

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#37] opened 2021-04-20 20:44 UTC
Clicking in the half-width strip around the edge of the diagram should only allow attachment, but at the moment it allows either rewriting or attachment.

For example, in this workspace, click in the lower attachment strip. You are given options to rewrite internally as well as to attach.
[filename_todo (15).zip](https://github.com/homotopy-io/homotopy-rs/files/6346569/filename_todo.15.zip)

**Comment by zrho** [comment] 2021-04-28 13:21
Duplicate of #4.

**Closed by zrho** 2021-04-28 13:21 UTC
Labels: bug
